UPDATE O_CODE SET MAIN_OBJ = REPLACE(MAIN_OBJ,' ','');

UPDATE O_CODE SET MAIN_OBJ = TRIM(MAIN_OBJ);

--select id, name, length(name)
--	from test1

SELECT LENGTH(MAIN_OBJ) FROM O_CODE;

SELECT * FROM O_CODE

SELECT TRIM(MAIN_OBJ) FROM O_CODE

DELETE FROM H_CODE_OBJ CASCADE;
DELETE FROM H_CODE_ANI CASCADE; 
DELETE FROM OBJ CASCADE;
DELETE FROM ANI CASCADE;
DELETE FROM O_CODE CASCADE;
DELETE FROM A_CODE CASCADE;

ALTER TABLE H_CODE_OBJ
MODIFY (MAIN_OBJ VARCHAR2(5));

INSERT INTO ANI (MAIN_ANI, ANI_DETAIL_CODE, ANI_CONTENT) VALUES ('가','061','잉글리쉬코카스파니엘');
INSERT INTO ANI (MAIN_ANI, ANI_DETAIL_CODE, ANI_CONTENT) VALUES ('가','049','아메리카코커스파니엘');